# Generated by Django 4.2 on 2023-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
